"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-03-24 18:30:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - initial schema ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.UniqueConstraint('username')
    )

    op.create_table('questions',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('domain', sa.String(), nullable=True),
        sa.Column('text', sa.String(), nullable=True)
    )

    op.create_table('reports',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('domain', sa.String(), nullable=True),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('facial_feedback', sa.String(), nullable=True),
        sa.Column('vocal_feedback', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    )

    op.create_table('interview_invitations',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('candidate_email', sa.String(), nullable=True),
        sa.Column('candidate_name', sa.String(), nullable=True),
        sa.Column('domain', sa.String(), nullable=True),
        sa.Column('invitation_token', sa.String(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), server_default=sa.text('0'), nullable=True),
        sa.Column('is_opened', sa.Boolean(), server_default=sa.text('0'), nullable=True),
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.UniqueConstraint('invitation_token')
    )

    # create indexes
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_questions_domain'), 'questions', ['domain'], unique=False)
    op.create_index(op.f('ix_interview_invitations_candidate_email'), 'interview_invitations', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_interview_invitations_invitation_token'), 'interview_invitations', ['invitation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - downgrade schema ###
    op.drop_index(op.f('ix_interview_invitations_invitation_token'), table_name='interview_invitations')
    op.drop_index(op.f('ix_interview_invitations_candidate_email'), table_name='interview_invitations')
    op.drop_index(op.f('ix_questions_domain'), table_name='questions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('interview_invitations')
    op.drop_table('reports')
    op.drop_table('questions')
    op.drop_table('users')
    # ### end Alembic commands ###
